apiVersion: v1
kind: Pod
metadata:
  name: my-web-pod
  labels:
    app: my-web-app
spec:
  volumes:
    - name: app
      emptyDir: {}
  initContainers:
    - name: download-file
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  containers:
  - name: my-web-container
    image: mvisangulov/server-nginx
    volumeMounts:
      - name: app
        mountPath: /app
    ports:
      - containerPort: 8000
